### ISSUE TITLE
Feature: built-in image diffs

### ISSUE THREAD

**Issue by johnboiles** [orta/Snapshots#28]
It'd be great to have a built in image diff-ing tool so you can get the overlaid diff of an image in addition to the (existing) clever mouse-over reveal UI.

An easy place to start would be using the [GHUnit CoreGraphics image diff-ing code](https://github.com/gh-unit/gh-unit/blob/master/Classes-iOS/GHViewTestCase.m#L202) I wrote a few years ago. It'd just need to be changed to use `NSImage` [APIs](http://stackoverflow.com/questions/9554207/draw-image-in-mac-os) instead of `UIGraphics*` APIs, but that should be super easy.

The fourth frame of this screenshot (from GHUnit) shows what this style diffs look like:

![screenshot](https://camo.githubusercontent.com/5149ae6bcaf9128327ea378503f311ec53ba757e/68747470733a2f2f7261772e6769746875622e636f6d2f67682d756e69742f67682d756e69742f6d61737465722f446f63756d656e746174696f6e2f696d616765732f696f732e706e67)

The way I imagine this to work is that the 'diff' button would become a toggle button that toggles between the original mouse-over reveal UI and the image diff. Maybe we add an additional button "Open in Kaleidoscope" so Kaleidoscope fans can still get there easily.

**Comment by johnboiles** [comment]
Hopefully I can get some time in the next few weeks to take a stab at this.

**Comment by johnboiles** [comment]
Oh ha! Looks like `FBSnapshotTestCase` already generates the diff image, using that same code linked above from GHUnit.

https://github.com/facebook/ios-snapshot-test-case/blob/master/FBSnapshotTestCase/Categories/UIImage%2BDiff.m

So this is just a matter of swapping out the mouse-over reveal ui with the diff'd image.

**Comment by orta** [comment]
:+1:

**Comment by daehn** [comment]
I gave this a try in https://github.com/orta/Snapshots/pull/39

**Comment by johnboiles** [comment]
Neat! I'll give it a go
