### ISSUE TITLE
Xcode 7.3 Compatibility

### ISSUE THREAD

**Issue by ashfurrow** [orta/Snapshots#36]
As noted in my [Eigen PR](https://github.com/artsy/eigen/pull/1353), Xcode 7.3 doesn't print test results to the debug console like it used to (they're sent to a log file). Snapshots plugin will need to either read that file or (and I think Orta talked to me about this) listen for notifications from Xcode about passed/failed tests. 

I'll try to take a stab at this, likely with https://github.com/ashfurrow/second_curtain/issues/40 for good measure.

**Comment by orta** [comment]
Probably best to setup a NSFileCoordinator for where-ever the logs come in to, I've wanted to make Snapshots standalone - and this it what it needed to do that. With that there's no need to build into Xcode.

**Comment by ashfurrow** [comment]
:+1: Cool, thanks for the guidance!

**Comment by ashfurrow** [comment]
Quick is also [looking at something similar](https://github.com/Quick/Quick/issues/494), I'll keep an eye on it to see what happens.

**Comment by ashfurrow** [comment]
scan/xcpretty/quick are all having issues with this. I'm not sure what the solution will be, I've looked through the generated log and plist test summaries and neither has the data as we need it. I'm not really qualified to go digging for which NSNotifications to listen to, so I'm going to have to put this aside for now.

**Comment by ashfurrow** [comment]
Loooooks like it might've just been a bug in Nimble: https://github.com/Quick/Nimble/pull/271 I'll keep on top of it.

**Comment by raphaelcruzeiro** [comment]
Any news on this? I kinda have a broken CI flow because of this issue (if there's anyway I can help, just let me know).

**Comment by ashfurrow** [comment]
Yes, the problem has been fixed on Nimble, but the [solution](https://github.com/Quick/Nimble/pull/271) is causing [new problems](https://github.com/Quick/Nimble/issues/273). Since the fix is in master, [we're using it](https://github.com/artsy/eigen/blob/60a027481da0ab74997ccbbb6428169f49b1d2a8/Podfile#L129) and it has solved this problem for now.

Actually I think we can close this issue now, since it's not a problem with this specific project. Thoughts?

**Comment by orta** [comment]
Aye - I think #37 also covers this from the perspective of doing it in snapshots itself.
