### ISSUE TITLE
Crash in Xcode 8.3

### ISSUE THREAD

**Issue by fjtrujy** [orta/Snapshots#41]
Hello,
In Xcode 8.3 they have changed the way to Log the Notifications and it is making crash the Xcode.
Basically the issue is because you're trying to append nil to a MutableString `[self.mutableLog appendString:log];`
Now Xcode 8.3 is returning a list of items, previously versions just returned a single item.

So, I have created already a PR that fix the crash, this is the link
https://github.com/orta/Snapshots/pull/40/

Thanks

**Comment by orta** [comment]
Thanks fixed by #40
